### ISSUE TITLE
La estructura de tu repositorio no cumple con lo solicitado

### ISSUE THREAD

**Issue by lucasljm2001** [pache0015/EstrD2022s2#1]
Es importante que aprendan a respetar las consignas al pie de la letra…

**Comment by pache0015** [comment]
"Lo ideal es que su usuario los identifique. Lo mejor de todo es "Apellido, Nombre" o "Nombre Apellido". Si ya tienen cuenta de Git con otro nombre, vean de cambiarla (salvo que sea un apodo por el que los podamos reconocer, como es mi caso... :D).
Luego deben crear un repositorio para las prácticas, con nombre "EstrD2022s2" y proceder como indica el tutorial mencionado. Si son recursantes y ya tienen un repo "EstrD2022s1", pueden renombrarlo y seguir usándolo (moviendo los archivos que correspondan a una carpeta que indique que son viejos).
Durante las clases les indicaremos a quién tienen que agregar como colaborador. Por ahora, al menos me agregan a mí, "fidel-ml" y seguramente luego agregarán a algún colaborador. "

Hola!
Ese texto que está dentro de "Tareas iniciales" es toda la instrucción que encontré acerca del repo.
Lo único que entiendo que no es lo "ideal" es el nombre de usuario pero no puedo cambiarlo. Está mi nombre además del nick de ser necesario. 
Si no es por esto, me podrías indicar por qué no cumple lo solicitado por favor?

Gracias

**Comment by lucasljm2001** [comment]
La entrega 1 tiene que estar en tp-1/tp-1.hs

**Comment by pache0015** [comment]
Corregido, gracias.

**Comment by lucasljm2001** [comment]
Resuelto
