### ISSUE TITLE
P.r1: En la funcion estaEnElMedio definis una subtarea innecesaria

### ISSUE THREAD

**Issue by lucasljm2001** [pache0015/EstrD2022s2#3]
Definis la subtarea esMismoDia, que si bien no esta mal, podrias resolver lo pedido en el enunciado con muchos menos casos de PM.

**Comment by pache0015** [comment]
Hola, entiendo lo que decís pero haciendo eso tendría que recurrir a igualar tipos de datos que yo mismo definí de la forma en la que lo hace el intérprete que si bien, a fines de la práctica no creo que afecte en algo pero las veces que me ha corregido Fidel si estoy en lo correcto, nos ha obligado a definir las igualaciones de los tipos que definimos.
De haber entendido mal el error podrías remarcarlo así lo consultpo ds por favor?
Muchas gracias!

**Comment by lucasljm2001** [comment]
Perdon, tu solucion es correcta
